spring:
  graphql:
    graphiql:
      enabled: true
    path: /graphql
#  kafka:
#    consumer:
#      bootstrap-servers: http://localhost:9091
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      bootstrap-servers: http://localhost:9091
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#  data:
#    redis:
#      host: ${REDIS_LOCAL_HOST}
#      port: ${REDIS_LOCAL_PORT}
  datasource:
    url: jdbc:mysql://gcu-mysql:3306/gcu?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true
    username: jjoon1379
    password: phj@1379
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 30
      idle-timeout: 30000
      max-lifetime: 1800000
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.format_sql: true
      hibernate.hibernate.default_batch_fetch_size: 100
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
  application:
    name: gcu
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 30796921504-plip806b4p5tcnbcl867slfggrvk745d.apps.googleusercontent.com        # 구글 클라이언트 ID
            client-secret: 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  # 구글 클라이언트 비밀
            scope: profile, email                # 요청할 권한
            redirect-uri: "http://localhost:8081/login/oauth2/code/google"  # 리디렉션 URI
            authorization-grant-type: authorization_code  # 인증 방식
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth  # 인증 URI
            token-uri: https://oauth2.googleapis.com/token                 # 토큰 URI
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo  # 사용자 정보 URI
jwt:
  secret: sdjfkljwekffnsaslfdfgkjlaklwdslkjfksdfjhsdfjsdsdfsklfsdjkfbsdlfs
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8081
logging:
  level:
    org.springframework.security: DEBUG